services:
  # Backend API Service
  backend:
    build: ./backend
    container_name: remocon-backend
    ports:
      - '3000:3000'
    env_file:
      - .env
    restart: unless-stopped

    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://localhost:3000/healthz']
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

    # 리소스 제한
    deploy:
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 256M

  # Frontend Service
  frontend:
    build:
      context: ./frontend
      target: production
    container_name: remocon-frontend
    ports:
      - '8080:3000'
    restart: unless-stopped
