services:
  # Backend API Service
  backend:
    build: ./backend
    container_name: remocon-backend
    ports:
      - '3000:3000'
    env_file:
      - .env
    restart: unless-stopped

    healthcheck:
      test:
        [
          'CMD',
          'python',
          '-c',
          'import httpx; import asyncio; import sys; response = asyncio.run(httpx.AsyncClient().get("http://localhost:3000/healthz")); sys.exit(0 if response.status_code == 200 else 1)',
        ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

    # 리소스 제한
    deploy:
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 256M

  # Frontend Service
  frontend:
    build:
      context: ./frontend
      target: development
    container_name: remocon-frontend
    ports:
      - '8080:3000'
    restart: unless-stopped
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
